version: '3.5'

services:
  lottery:
    container_name: lottery
    build:
      context: .
      dockerfile: build/Dockerfile.local
    volumes:
      - ./:/src/go
    ports:
      - 80:8080
    depends_on:
      - elasticsearch
    working_dir: /src/go
    command: reflex -c reflex.conf

  elasticsearch:
    image: elasticsearch:6.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
